services:
  - type: web
    name: bfhl-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: USER_ID
        value: niranjanBalaguru_22012006
      - key: EMAIL_ID
        value: nb1999@srmist.edu.in
      - key: ROLL_NUMBER
        value: RA2311003010050